# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/bionic64"

  # VM settings
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2 php mysql-server php-mysql libapache2-mod-php wget unzip

    cd /var/www/html
    sudo rm index.html
    wget https://wordpress.org/latest.zip
    unzip latest.zip
    sudo mv wordpress/* .
    rm -rf wordpress latest.zip

    sudo chown -R www-data:www-data /var/www/html

    # Create MySQL database for WordPress
    mysql -u root <<MYSQL_SCRIPT
CREATE DATABASE wordpress DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'wppassword';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost';
FLUSH PRIVILEGES;
MYSQL_SCRIPT

    # Create wp-config.php
    cp wp-config-sample.php wp-config.php
    sed -i "s/database_name_here/wordpress/" wp-config.php
    sed -i "s/username_here/wpuser/" wp-config.php
    sed -i "s/password_here/wppassword/" wp-config.php

    # Restart Apache
    sudo systemctl restart apache2
  SHELL
end
