# Vagrantfile for creating a CentOS box
Vagrant.configure("2") do |config|
  # Use the official CentOS box
  config.vm.box = "centos/7"

  # Optional: Configure the VM's network settings
  
  config.vm.network "forwarded_port", guest: 80, host: 8080  # Forward port 80 to host port 8080
 #config.vm.network "private_network", type: "dhcp"  # Use DHCP for private network
 # config.vm.network "private_network", ip: "192.168.0.0"  # Assign static private IP
  # Optional: Configure the VM's memory and CPU
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # Set memory to 1024 MB
    vb.cpus = 2        # Set number of CPUs to 1
  end

  # Optional: Provisioning script (if needed)
   config.vm.provision "shell", inline: <<-SHELL
   
     yum update -y
   SHELL
end
